app/models.py
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class Student(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    student_ref = db.Column(db.Integer, nullable=False, unique=True)
    name = db.Column(db.Text, nullable=False)
    email = db.Column(db.Text)
    password = db.Column(db.Text)
    grades = db.relationship('Grade', backref='students')

    def __repr__(self):
        return '<Student {}>'.format(self.student_id)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Teacher(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher_ref = db.Column(db.Text, nullable=False)
    title = db.Column(db.Text)
    name = db.Column(db.Text)
    courses = db.relationship('Course', backref='teachers')

    def __repr__(self):
        return '<Teacher {} {}>'.format(self.first_name, self.last_name)


class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_code = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text, nullable=False)
    teacher_id = db.Column(db.Integer, db.ForeignKey('teacher.id'), nullable=False)
    grades = db.relationship('Grade', backref='courses')

    def __repr__(self):
        return '<Course {}>'.format(self.code, self.name)


class Grade(db.Model):
    student_id = db.Column(db.Integer, db.ForeignKey('student.id'), nullable=False, primary_key=True)
    course_id = db.Column(db.Integer, db.ForeignKey('course.id'), nullable=False, primary_key=True)
    grade = db.Column(db.Text)

    def __repr__(self):
        return '<Grade {}>'.format(self.grade)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError

from app.models import Student


class SignupForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    student_ref = StringField('Student ID number',
                              validators=[DataRequired(message="Please enter your student ID number")])
    email = StringField('Email address', validators=[DataRequired(), Email(message='Valid email address required')])
    password = PasswordField('Password',
                             validators=[DataRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Repeat Password')
    submit = SubmitField('Sign Up')

    def validate_student_ref(self, student_ref):
        student = Student.query.filter_by(student_ref=student_ref.data).first()
        if student is not None:
            raise ValidationError(
                'An account is already registered for that student ID. Please use a different student reference number.')

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

from config import DevConfig

# The SQLAlchemy object is defined globally
db = SQLAlchemy()


def page_not_found(e):
    return render_template('404.html'), 404


def internal_server_error(e):
    return render_template('500.html'), 500


def create_app(config_class=DevConfig):
    """
    Creates an application instance to run
    :return: A Flask object
    """
    app = Flask(__name__)

    # Configure app wth the settings from config.py
    app.config.from_object(config_class)

    # Initialise the database and create tables
    db.init_app(app)

    from populate_db import populate_db
    from app.models import Teacher, Student, Course, Grade
    with app.app_context():
        db.create_all()
        populate_db()

    # Register error handlers
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    # Register Blueprints
    from app.main.routes import bp_main
    app.register_blueprint(bp_main)

    return app

app/main/routes.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from sqlalchemy.exc import IntegrityError

from app import db
from app.main.forms import SignupForm
from app.models import Course, Student

bp_main = Blueprint('main', __name__)


@bp_main.route('/')
def index():
    return render_template('index.html')


@bp_main.route('/signup/', methods=['POST', 'GET'])
def signup():
    form = SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        user = Student(name=form.name.data, email=form.email.data, student_ref=form.student_ref.data)
        user.set_password(form.password.data)
        try:
            db.session.add(user)
            db.session.commit()
            flash('You are now a registered user!')
            return redirect(url_for('main.index'))
        except IntegrityError:
            db.session.rollback()
            flash('ERROR! Unable to register {}. Please check your details are correct and resubmit'.format(form.email.data), 'error')
    return render_template('signup.html', form=form)


@bp_main.route('/courses', methods=['GET'])
def courses():
    courses = Course.query.all()
    # courses = Course.query.join(Teacher).with_entities(Course.course_code, Course.name, Teacher.name.label('teacher_name')).all()
    return render_template("courses.html", courses=courses)


@bp_main.route('/search', methods=['POST', 'GET'])
def search():
    if request.method == 'POST':
        term = request.form['search_term']
        if term == "":
            flash("Enter a name to search for")
            return redirect('/')
        results = Student.query.filter(Student.email.contains(term)).all()
        if not results:
            flash("No students found with that name.")
            return redirect('/')
        return render_template('search_results.html', results=results)
    else:
        return redirect(url_for('main.index'))


@bp_main.route('/student/<name>')
def show_student(name):
    user = Student.query.filter_by(name=name).first_or_404(description='There is no user {}'.format(name))
    # user = Student.query.filter_by(name=name).first_or_404()
    return render_template('show_student.html', user=user)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
<nav class="navbar navbar-expand bg-primary navbar-dark">
    <a class="navbar-brand" href="#">CS Courses</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.signup') }}">Sign up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.courses') }}">Courses</a>
        </li>
    </ul>
    <form class="form-inline ml-auto" action="search" method="post">
        <input class="form-control" type="search" placeholder="Enter student name" aria-label="Search" name="search_term">
        <button class="btn btn-primary btn-outline-light" type="submit">Search</button>
    </form>
</nav>
<br>
<div role=main class="container">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert-warning list-unstyled">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content %}
    {# Child pages add page specific content here #}
    {% endblock %}
</div>
</body>
</html>

app/templates/base_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
</body>
</html>

app/templates/courses.html
{% extends "base.html" %}
{% block title %}Courses{% endblock %}
{% block content %}
{% if courses|length %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Code</th>
        <th scope="col">Course Name</th>
        <th scope="col">Teacher</th>
    </tr>
    </thead>
    <tbody>
    {% for course in courses %}
    <tr>
        <td>{{ course.course_code }}</td>
        <td>{{ course.name }}</td>
        <td>{{ course.teacher_id }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Sorry, no courses are available at this time</p>
{% endif %}
{% endblock %}

app/templates/index.html
{# Inherit a parent template called base.html #}
{% extends "base.html" %}
{# Add the title for this page #}
{% block title %}Home{% endblock %}
{# Add the content for this page #}
{% block content %}
    <h1>Welcome</h1>
{% endblock %}

app/templates/search_results.html
{% extends "base.html" %}
{% block title %}Search results{% endblock %}
{% block content %}
{% if results|length %}
{# Variable is not empty #}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Student name</th>
        <th scope="col">Email</th>
    </tr>
    </thead>
    <tbody> {% for result in results %}
    <tr>
        <td>{{ result.name }}</td>
        <td>{{ result.email }}</td>
    </tr>
     {% endfor %}
    </tbody>
</table>
{% else %}
{# Variable is empty #}
<p>Sorry, no students found</p>
{% endif %}
{% endblock %}

app/templates/show_student.html
{% extends "base.html" %}
{% block title %}Student details{% endblock %}
{% block content %}
<h1>Account details for {{ user.name }}</h1>
<p>Email: {{ user.email }}</p>
<p>Student ID number: {{ user.student_ref }}</p>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %} Signup {% endblock %}
{% block content %}
{# Display the form validation errors #}
{% if form.errors %}
    <ul class="alert-warning list-unstyled">
        {% for field_name, field_errors in form.errors|dictsort if field_errors %}
            {% for error in field_errors %}
                <li>{{ form[field_name].label }}: {{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
{% endif %}
{# Display the form, turn off HTML validation #}
{# The (class_="") after a form field is used to apply css style to the element, in this case a bootstrap style #}
<form method="post" novalidate>
    {{ form.csrf_token }}
    {{ form.name.label }}{{ form.name(class="form-control") }}
    {{ form.student_ref.label }}{{ form.student_ref(class="form-control") }}
    {{ form.email.label }}{{ form.email(class="form-control") }}
    {{ form.password.label }}{{ form.password(class="form-control") }}
    {{ form.confirm.label }}{{ form.confirm(class="form-control") }}
    <br>{{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}